// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5l4IKJLr2g3Co_j3fHI4RYPGkQPAQBpU',
    appId: '1:530302670295:web:b9a56486c1f57541b66792',
    messagingSenderId: '530302670295',
    projectId: 'fir-series-b33e2',
    authDomain: 'fir-series-b33e2.firebaseapp.com',
    storageBucket: 'fir-series-b33e2.firebasestorage.app',
    measurementId: 'G-W9RH5FTZWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9kZi9gG5QWjuyaCmEGmNBkiPPqjyJFU',
    appId: '1:530302670295:android:affd31154235caf0b66792',
    messagingSenderId: '530302670295',
    projectId: 'fir-series-b33e2',
    storageBucket: 'fir-series-b33e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIWMGWgioEvTOa0YAv1RFNhYzB0wtQyQ',
    appId: '1:530302670295:ios:51fb2a13c59b6ebdb66792',
    messagingSenderId: '530302670295',
    projectId: 'fir-series-b33e2',
    storageBucket: 'fir-series-b33e2.firebasestorage.app',
    iosBundleId: 'com.qcode.community',
  );
}
